name: Production release

# Cancel previous workflows
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  release:
    types: 
      - released

jobs:
  version_bump:
    name: Bump package.json version
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@master
      - name: get version name
        id: version
        run: echo "::set-output name=version::${GITHUB_REF_NAME##*/}"
      - name: bump version
        uses: dmikey/package-json-version@v0.0.2
        with:
          version: ${{ steps.version.outputs.version }}
          git-tag-version: true
  
  publish:
    name: Publish module
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        run: echo "todo publish module npm"