name: Production release

# Cancel previous workflows
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  release:
    types: 
      - released

jobs:
  version_bump:
    name: Bump package.json version
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@master

      - name: bump version
        uses: dmikey/package-json-version@v0.0.2
        with:
          version: '${{ github.ref_name }}'
  
  publish:
    name: Publish module
    runs-on: ubuntu-latest
    needs: version_bump
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          registry-url: https://registry.npmjs.org
          cache: yarn

      - uses: simenandre/publish-with-yarn@v1
        with:
          npm-auth-token: ${{ secrets.NPM_TOKEN }}